name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit Tests (Offline, Mocked)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest (unit tests only)
        run: pytest tests/unit_offline --cov=ingest_pipeline --cov-report=term-missing

  integration-tests:
    name: Integration Tests (Real GCP)
    runs-on: ubuntu-latest
    # This job will only run if the GCP Service Account Key secret is configured
    if: ${{ secrets.GCP_SA_KEY != '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure GCP Credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcp_key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcp_key.json"
          gcloud auth activate-service-account --key-file=$HOME/gcp_key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Run pytest (integration tests)
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GCP_REGION }}
          TEMP_BUCKET: ${{ secrets.GCP_TEMP_BUCKET }}
        run: pytest tests/integration -m integration